input_file: ""
output_file: ""

# data prep
det_props: "/home/awilkins/larnd-sim/larnd-sim/larndsim/detector_properties/ndlar-module.yaml"
pixel_layout: "/home/awilkins/larnd-sim/larnd-sim/larndsim/pixel_layouts/multi_tile_layout-3.0.40.yaml"
vmap_path: "/home/awilkins/larnd_infill/larnd_infill/voxel_maps/vmap_zdownresolution10.yml"
data_prep_type: "reflection"
scalefactors: [ 0.005780346820809248, 0.5 ] # 1/173, 1/2
forward_facing_anode_zshift: 0.38
backward_facing_anode_zshift: -0.38

# model
n_feats_in: 2 # adc
n_feats_out: 1 # adc
adc_threshold: 4 # prune all predicted adc <= 1 in final layer
load_G: "/home/awilkins/larnd_infill/larnd_infill/saved_models/gps_single_muon_zdownsample10-exp1_2-netG_best_epoch78.pth"
model_params:
  final_layer: "hardtanh"
  enc_ch: [8, 16, 32, 64, 128]
  dec_ch: [8, 16, 32, 64, 128]
  nonlinearity: "elu"
  extra_convs: False
  norm_layer: "instance"
  use_dropout: False
  enc_ks: [5, 3, 3]
  dec_ks: [5, 3, 3]

# misc
batch_size: 2
device: "cuda:0"
cache_dir: "/share/rcifdata/awilkins/cache"

